<a href="https://colab.research.google.com/github/saykim/006958/blob/master/pytorch_nn_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## nn.Module로 구현하는 선형회귀

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import numpy as np


In [8]:
boston = datasets.load_boston()

In [9]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [10]:
x = boston['data']
y = boston['target']

In [11]:
x.shape

(506, 13)

In [12]:
torch.manual_seed(1)

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size = .2)

In [17]:
scaler = StandardScaler()

In [18]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [19]:
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)

x_test = torch.FloatTensor(x_test)
y_test = torch.FloatTensor(y_test)

In [22]:
x_train.shape

torch.Size([404, 13])

In [45]:
#model
model = nn.Linear(13,1)

In [46]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2080,  0.0033, -0.1461,  0.1426, -0.1472,  0.0816, -0.0801, -0.0304,
         -0.2666, -0.1322,  0.1505, -0.0674,  0.2763]], requires_grad=True), Parameter containing:
tensor([0.2223], requires_grad=True)]


In [47]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [48]:
n_epochs =1000

for epoch in range(n_epochs+1):
    pred = model(x_train)
    cost = F.mse_loss(pred, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('epoch {:.4f}/{}, Cost {:.6f}'.format(epoch, n_epochs, cost.item()))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: Using a target size (torch.Size([404])) that is different to the input size (torch.Size([404, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  """


epoch 0.0000/1000, Cost 596.641479
epoch 100.0000/1000, Cost 95.856911
epoch 200.0000/1000, Cost 87.036545
epoch 300.0000/1000, Cost 86.878334
epoch 400.0000/1000, Cost 86.874519
epoch 500.0000/1000, Cost 86.874016
epoch 600.0000/1000, Cost 86.873787
epoch 700.0000/1000, Cost 86.873657
epoch 800.0000/1000, Cost 86.873581
epoch 900.0000/1000, Cost 86.873535
epoch 1000.0000/1000, Cost 86.873505


In [35]:
cost.squeeze().detach()

tensor(86.8734)

In [32]:
cost.item()

86.87342834472656

In [33]:
model

Linear(in_features=13, out_features=1, bias=True)

In [36]:
pred.squeeze()

tensor([22.7943, 22.7981, 22.7937, 22.7958, 22.7975, 22.8017, 22.8042, 22.7945,
        22.7991, 22.7942, 22.8033, 22.8011, 22.7963, 22.7969, 22.7997, 22.7953,
        22.7973, 22.7987, 22.7901, 22.7985, 22.7929, 22.7878, 22.8008, 22.7980,
        22.7976, 22.7975, 22.7994, 22.7980, 22.8094, 22.7857, 22.7939, 22.7876,
        22.8025, 22.7945, 22.8052, 22.8020, 22.7975, 22.7949, 22.7964, 22.7929,
        22.7964, 22.7937, 22.7987, 22.7996, 22.7986, 22.7999, 22.7950, 22.7976,
        22.7985, 22.7991, 22.7951, 22.7895, 22.7983, 22.8012, 22.7950, 22.7999,
        22.7969, 22.7954, 22.8002, 22.7984, 22.7959, 22.7979, 22.8025, 22.7959,
        22.8008, 22.7944, 22.7947, 22.7903, 22.7749, 22.7911, 22.8000, 22.7893,
        22.7951, 22.7898, 22.7883, 22.7984, 22.7901, 22.8014, 22.8022, 22.7986,
        22.7986, 22.7983, 22.8015, 22.7940, 22.7980, 22.7963, 22.7921, 22.7919,
        22.8006, 22.7895, 22.7953, 22.7974, 22.7983, 22.7990, 22.7978, 22.7920,
        22.7978, 22.8022, 22.8023, 22.79

## class 로 파이토치 모델 구현

In [49]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import numpy as np


### 데이터 불러오기

In [50]:
boston = datasets.load_boston() #scikit learn 모델 불러오기

x = boston['data']
y = boston['target']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size = .2) #train/test 분리

scaler = StandardScaler() #scaler

x_train = scaler.fit_transform(x_train) # 데이터 scaler 로 변환
x_test = scaler.transform(x_test)


x_train = torch.FloatTensor(x_train) #torch로 변환
y_train = torch.FloatTensor(y_train)

x_test = torch.FloatTensor(x_test)
y_test = torch.FloatTensor(y_test)


In [52]:
x_train.size()

torch.Size([404, 13])

In [74]:
model = nn.Linear(13,1) #(input_dim, outout_dim) 

> 모델 선언 및 초기화는 위에 처럼 모델을 만들었지만, 클래스를 이요하여 아래처럼 만든다

In [75]:
class LinearRegressionModel(nn.Module): #torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(13,1)

    def forward(self,x):
        return self.linear(x) 


In [78]:
model = LinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [79]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.2210, -0.1264, -0.0849,  0.1186,  0.0507,  0.0685,  0.2768,  0.2703,
          0.1892,  0.0088, -0.1919,  0.2168, -0.0694]], requires_grad=True), Parameter containing:
tensor([-0.0224], requires_grad=True)]


In [80]:
n_epochs = 200

for epoch in range(n_epochs+1):
    pred = model(x_train)
    cost = F.mse_loss(pred, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 50 ==0:
        print('epcoch : {}/{}, cost : {:.2f}'.format(epoch, n_epochs, cost.item()))

epcoch : 0/200, cost : 607.79
epcoch : 50/200, cost : 155.98
epcoch : 100/200, cost : 96.06
epcoch : 150/200, cost : 88.10
epcoch : 200/200, cost : 87.04


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: Using a target size (torch.Size([404])) that is different to the input size (torch.Size([404, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  """


In [65]:
y_pred = model(x_test)
y_pred.shape

torch.Size([102, 1])

In [63]:
F.mse_loss(y_pred, y_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Using a target size (torch.Size([102])) that is different to the input size (torch.Size([102, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  """Entry point for launching an IPython kernel.


tensor(75.0456, grad_fn=<MseLossBackward>)

In [66]:
y_test.shape

torch.Size([102])